services:
  database-mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=myappdocker
    ports:
      - '27017:27017'
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  nodeserver:
    build:
      context: ./
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DELAY=1000
      - MONGO_URL=mongodb://database-mongodb/myappdocker
      - HOST=http://localhost
      - REDIS_URL=redis://redis:6379
    ports:
      - 8080:8080
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
        - "80:80"